spring:
  application:
    name: commerce
  profiles:
    active: local

# portone
portone:
  secret:
    api: ${API_CODE}
    webhook: ${WEBHOOK_CODE}

# jwt
jwt:
  secret: ${JWT_SECRET}

# eventListener
delay: 30

# Swagger
server:
  forward-headers-strategy: framework

springdoc:
  packages-to-scan: lsk.commerce
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    with-credentials: true
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs